"""Added Phase 2 File Uploads and SLA fields

Revision ID: 993026265a8b
Revises: 70be85324ecb
Create Date: 2026-05-10 13:26:47.200562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993026265a8b'
down_revision = '70be85324ecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sla_deadline', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sla_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('escalation_level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('resolved_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('escalation_level')
        batch_op.drop_column('sla_status')
        batch_op.drop_column('sla_deadline')

    # ### end Alembic commands ###
