"""Added indexes to Complaint table

Revision ID: d5ee43d29391
Revises: 910f08caf7cf
Create Date: 2026-05-10 13:49:25.502481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5ee43d29391'
down_revision = '910f08caf7cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaint_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_sentiment'), ['sentiment'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_sla_deadline'), ['sla_deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaint_status'))
        batch_op.drop_index(batch_op.f('ix_complaint_sla_deadline'))
        batch_op.drop_index(batch_op.f('ix_complaint_sentiment'))
        batch_op.drop_index(batch_op.f('ix_complaint_priority'))
        batch_op.drop_index(batch_op.f('ix_complaint_department_id'))
        batch_op.drop_index(batch_op.f('ix_complaint_date'))

    # ### end Alembic commands ###
